# Utiliza una imagen base de Go para compilar el binario
FROM golang:1.21.0 AS builder

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos go.mod y go.sum y descarga las dependencias
COPY go.mod go.sum ./
RUN go mod download

# Copia el código fuente del proyecto
COPY . .

# Compila el binario del microservicio, especificando el archivo principal
RUN go build -o usersManagement ./main.go

# Verifica que el binario se ha compilado correctamente
RUN ls -la /app

# Utiliza una imagen base más pequeña para ejecutar el binario
FROM alpine:latest

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /root/

# Copia el binario compilado desde la etapa de construcción
COPY --from=builder /app/usersManagement .

# Verifica que el binario se ha copiado correctamente
RUN ls -la /root

# Expone el puerto en el que el microservicio escucha
EXPOSE 8080

# Comando para ejecutar el binario
CMD ["./usersManagement"]